apiVersion: v1
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
<<<<<<< HEAD
          address: 10.61.0.17
=======
          address: 10.61.0.11
>>>>>>> a0a6c1b7f32fa9c50f4edac91bfc74fc5dc9db2c
          port: 22
        public:
          address: 127.0.0.1
          port: 2222
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
<<<<<<< HEAD
          address: 10.61.0.18
=======
          address: 10.61.0.12
>>>>>>> a0a6c1b7f32fa9c50f4edac91bfc74fc5dc9db2c
          port: 22
        public:
          address: 127.0.0.1
          port: 2223
kind: List
